Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/policies/application_policy.rb
app/policies/mood_policy.rb
config/puma.rb
test/policies/mood_policy_test.rb

Installed pundit and generated pundit policy file

Implement pundit

---

Gemfile
Gemfile.lock
app/models/mood.rb
db/migrate/20200525050334_create_moods.rb
db/migrate/20200525052627_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
db/migrate/20200525052628_add_missing_unique_indices.acts_as_taggable_on_engine.rb
db/migrate/20200525052629_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb
db/migrate/20200525052630_add_missing_taggable_index.acts_as_taggable_on_engine.rb
db/migrate/20200525052631_change_collation_for_tag_names.acts_as_taggable_on_engine.rb
db/migrate/20200525052632_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb
db/schema.rb
test/models/mood_test.rb

created model and activities tag

---

app/controllers/moods_controller.rb
test/controllers/moods_controller_test.rb

controller mood added

---

db/seeds.rb

done creating fake seeds

---

app/controllers/moods_controller.rb
app/views/moods/index.html.erb

Added index action

---

app/policies/mood_policy.rb
app/views/moods/index.html.erb

Modified index policy

---

app/controllers/application_controller.rb
app/controllers/moods_controller.rb
app/policies/mood_policy.rb
app/views/moods/insights.html.erb

Added insights action

---

app/controllers/moods_controller.rb
app/models/mood.rb
app/policies/mood_policy.rb
app/views/moods/index.html.erb
app/views/moods/new.html.erb

form add moods and save

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/controllers/pages_controller.rb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/pages/test.html.erb
app/views/shared/_navbar.html.erb

check please @Katsulincon @pins-thoo

Done structuring the navbar

---

app/controllers/moods_controller.rb
app/models/user.rb
app/policies/mood_policy.rb
app/views/moods/show.html.erb

Added show action

---

app/controllers/moods_controller.rb
app/models/user.rb
app/views/moods/index.html.erb

updated average mood count views

---

app/assets/stylesheets/components/_cards.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Moved the navbar to the partial document and created the card component. check please @pins-thoo @Katsulincon

Updated the navbar and created the card component

---

app/views/shared/_navbar.html.erb

Added link to navbar

---

app/assets/stylesheets/components/_cards.scss
app/views/pages/home.html.erb

@check please @pins-thoo @Katsulincon

Added stye to card component

---

app/controllers/moods_controller.rb
app/views/moods/index.html.erb
db/seeds.rb

added more seeds

---

app/views/moods/new.html.erb

Just added container to new view

---

app/assets/stylesheets/components/_containers.scss
app/assets/stylesheets/components/_index.scss
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

Fix footer. please check @Katsulincon @pins-thoo

Fix footer

---

app/views/moods/index.html.erb

removed container from the index page @Katsulincon @pins-thoo

Remove cntainer from the index page

---

Gemfile
Gemfile.lock
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_insights.scss
app/controllers/moods_controller.rb
app/javascript/packs/application.js
app/policies/mood_policy.rb
app/views/moods/insights.html.erb
package.json
yarn.lock

Added top activities. I'm going to fix styling later again.

Style insights page

---

app/controllers/moods_controller.rb
app/javascript/packs/application.js
app/javascript/packs/chartkick.js
app/models/user.rb
app/views/layouts/application.html.erb
app/views/moods/insights.html.erb

Added weekly-graph

---

app/models/user.rb
app/views/moods/insights.html.erb

Fixed error

---

app/assets/stylesheets/components/_cards.scss
app/views/moods/index.html.erb
app/views/pages/home.html.erb

tags updated

---

app/controllers/moods_controller.rb
app/views/moods/insights.html.erb

@pins-thoo @yusuke0127 
I will refactor month graph tomorrow.

Added month graph

---

app/assets/stylesheets/components/_smileys.scss
app/views/moods/new.html.erb
app/views/pages/home.html.erb

Added the smileys we wanted to the form

Change the smileys in the form

---

db/seeds.rb

Increased seeds

---

app/assets/stylesheets/pages/_insights.scss
app/controllers/moods_controller.rb
app/models/user.rb
app/views/moods/insights.html.erb

I added year graph. I still need to work on styling later.

Added year graph

---

app/assets/stylesheets/components/_smileys.scss
app/controllers/moods_controller.rb
app/views/moods/new.html.erb
app/views/pages/home.html.erb

check please @Katsulincon @pins-thoo

Added smileys to the form

---

app/assets/stylesheets/pages/_insights.scss
app/controllers/moods_controller.rb
app/views/moods/insights.html.erb
app/views/moods/new_tag.html.erb

Added javascript and colors for the activity list

---

app/assets/stylesheets/pages/_insights.scss
app/views/moods/insights.html.erb

Changed color pattern

---

app/controllers/moods_controller.rb
app/views/moods/show.html.erb

Added cards

---

app/views/moods/show.html.erb

Replaced the head text and put date

---

Gemfile
Gemfile.lock
app/controllers/moods_controller.rb
config/environments/development.rb

2 seconds faster now... but still feels slow

Added bullet gem

---

app/controllers/application_controller.rb
app/controllers/moods_controller.rb
app/views/moods/habits.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

added good and bad habits

---

app/controllers/moods_controller.rb

Added includes-taggings to index query

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/pages/_insights.scss
app/controllers/moods_controller.rb
app/views/moods/index.html.erb
app/views/moods/insights.html.erb
app/views/moods/show.html.erb

Index page

---

app/models/mood.rb
app/views/moods/index.html.erb
app/views/moods/insights.html.erb
app/views/moods/new.html.erb
app/views/moods/show.html.erb
config/routes.rb

Change text on index

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_smileys.scss
app/views/moods/new.html.erb
app/views/moods/new_smiley.html.erb

check please @pins-thoo @Katsulincon

Fix the bugs in the form and added style

---

app/assets/stylesheets/components/_cards.scss

Fixed cards width

---

app/controllers/moods_controller.rb
app/views/moods/habits.html.erb

Changed authentication

---

app/assets/stylesheets/components/_containers.scss
app/assets/stylesheets/components/_form.scss
app/javascript/components/smiley_selector.js
app/javascript/components/smileylink.js
app/javascript/packs/application.js
app/views/moods/new.html.erb
app/views/moods/new_smiley.html.erb

Added style to forms @Katsulincon

Added style to forms

---

app/views/moods/insights.html.erb

Widened the tab

---

app/javascript/packs/application.js

Fix some bugs

---

app/assets/stylesheets/pages/_insights.scss
app/views/moods/insights.html.erb

Changed activities color

---

app/assets/stylesheets/components/_containers.scss
app/assets/stylesheets/components/_form.scss
app/views/moods/calendar.html.erb

add some style

---

app/controllers/moods_controller.rb
app/views/moods/index.html.erb

I'll do styling and refactor later.

Added suggestion in index page

---

app/assets/stylesheets/pages/_insights.scss
app/controllers/moods_controller.rb
app/models/user.rb
app/views/moods/insights.html.erb

updated the insights page weekly mood to line chart

updated insights for weekly

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_navbar.scss

haven't touch the progress bar yet. Will do it later tonight

updated the feedback css styling except for progress bar

---

app/assets/stylesheets/pages/_insights.scss
app/controllers/moods_controller.rb
app/models/user.rb
app/views/moods/insights.html.erb

updated insights page. all looking good hopefully :)

updated insights page

---

app/assets/stylesheets/components/_cards.scss
app/views/moods/index.html.erb

Styled suggestion card

---

app/controllers/moods_controller.rb
app/jobs/send_friend_message_job.rb
app/models/mood.rb
app/views/shared/_navbar.html.erb
db/schema.rb

Can send sad message to friends

---

app/jobs/send_message_to_pins_job.rb
test/jobs/send_message_to_pins_job_test.rb

Created send message job

---

config/environments/production.rb

Setup https

---

app/controllers/api/v1/line_bot_controller.rb

Fixed line chatbot error

---

app/controllers/api/v1/base_controller.rb
app/controllers/api/v1/line_bot_controller.rb

Added debugging code

---

app/controllers/api/v1/line_bot_controller.rb

Changed debugging code

---

app/views/users/community.html.erb

Added link to LINE logo

---

app/views/users/community.html.erb

Change community to timeline @Katsulincon

Change community to timeline

---

app/jobs/send_message_to_pins_job.rb

Change sentence

---

app/assets/stylesheets/pages/_community.scss
app/views/users/community.html.erb

Display average

---

db/seeds.rb

Added moods for teachers

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_smileys.scss
app/helpers/application_helper.rb
app/views/moods/index.html.erb

Change emojis from the index card to the 3d emojis @Katsulincon @pins-thoo

Change emojis from the index card to the 3d emojis

---

app/assets/stylesheets/components/_smileys.scss
app/assets/stylesheets/pages/_community.scss
app/views/users/community.html.erb
db/schema.rb

Change card emoji with the 3d emoji @Katsulincon @pins-thoo

Change card emoji with the 3d emoji

---

app/assets/stylesheets/components/_smileys.scss
app/assets/stylesheets/pages/_insights.scss
app/views/moods/insights.html.erb

Change emoji of charts in insights @Katsulincon @pins-thoo

Change emoji of charts in insights

---

app/assets/stylesheets/components/_smileys.scss

home page fixed

---

app/assets/stylesheets/components/_smileys.scss
app/assets/stylesheets/pages/_insights.scss
app/views/moods/insights.html.erb

Change emoji in year month chart @Katsulincon @pins-thoo

Change emoji in year month chart

---

app/views/users/community.html.erb

Changed line url and added if condition

---

app/controllers/api/v1/line_bot_controller.rb

Deleted binding.pry

---

app/views/moods/habits.html.erb
app/views/users/community.html.erb

Fix some minor style @Katsulincon @pins-thoo

Fix some minor style

---

app/views/users/community.html.erb

Changed the line link

---

app/views/users/community.html.erb

added line logo every cards

---

app/assets/stylesheets/components/_cards.scss
app/javascript/components/smiley_bounce.js
app/views/moods/new.html.erb
app/views/moods/show.html.erb

added notes to the show page @Katsulincon @pins-thoo

added notes to the show page

---

app/assets/stylesheets/components/_cards.scss
app/views/moods/insights.html.erb

Fix the emojis in the chart @Katsulincon @pins-thoo

Fix the emojis in the chart

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_smileys.scss

Made icon bigger and add opacity to time

---

app/controllers/api/v1/line_bot_controller.rb
app/jobs/send_friend_message_job.rb
app/jobs/send_message_to_pins_job.rb
app/jobs/send_mood_event_job.rb

Added sticker to the replies @Katsulincon

Added sticker to the replies

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_smileys.scss
app/views/moods/new_smiley.html.erb

Fix home page

---

app/jobs/send_message_to_pins_job.rb
app/jobs/send_mood_event_job.rb

Fix some bugs for line chat bot @Katsulincon

Fix some bugs for line chat bot

---

app/controllers/api/v1/line_bot_controller.rb

Add stickers to messages @Katsulincon

Add stickers to messages

---

app/javascript/components/change_check.js

Made spinner spin @Katsulincon

Made spinner spin

---

app/assets/stylesheets/pages/_habits.scss

Adjusted media screen on habits page

---

app/assets/stylesheets/components/_form.scss
app/views/moods/new.html.erb

Centered the form for the notes @Katsulincon @pins-thoo

Centered the form for the notes

---

app/assets/stylesheets/pages/_insights.scss
app/views/moods/insights.html.erb

Made the emojis in the insights page responsive. check please! @Katsulincon @pins-thoo

Made the emojis in the insights page responsive

---

app/assets/stylesheets/pages/_sign_in.scss
app/views/devise/registrations/new.html.erb
app/views/devise/shared/_links.html.erb

Add style to the form @Katsulincon @pins-thoo

Add style to the form

---

app/controllers/moods_controller.rb

Changed if statement

---

app/views/shared/_navbar.html.erb

Removed google logo from the navbar @Katsulincon @pins-thoo

Removed google logo from the navbar

---

app/views/moods/habits.html.erb

Fixed some view logic for the habits page check please @Katsulincon @pins-thoo

Fix the habits page
